### ISSUE TITLE
IfSearch Console for Channel

### ISSUE THREAD

**Issue by TonyZOtto** [TonyZOtto/ottoZcode#22]
Components:

- [ ] Engine Management TonyZOtto/Eclipse6#23 
- [ ] Image Acquisition TonyZOtto/Eclipse6#24 
- [ ] Frame Processing TonyZOtto/Eclipse6#25
- [ ] Face Processing TonyZOtto/Eclipse6#26
- [ ] Vector Matching TonyZOtto/Eclipse6#27
- [ ] Results TonyZOtto/Eclipse6#28 
- [ ] INDIbase Enrollment TonyZOtto/Eclipse6#29
- [ ] INDIbase Vector Search TonyZOtto/Eclipse6#30
- [ ] INDIbase Management TonyZOtto/Eclipse6#31
- [ ] Analytics TonyZOtto/Eclipse6#32
